services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mariadb
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - "5173:5173" 
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
  mariadb:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tablebook
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./default.sql:/docker-entrypoint-initdb.d/default.sql  # Mappa il file SQL per la creazione del DB


volumes:
  mariadb_data: